/*

    qw - A minimalistic text editor

    ttcdt <dev@triptico.com>

    This software is released into the public domain.
    NO WARRANTY. See file LICENSE for details.

*/

#ifndef QW_KEY_H
#define QW_KEY_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    QW_KEY_NONE,
    QW_KEY_CHAR,
    QW_KEY_DEL,
    QW_KEY_UP,
    QW_KEY_DOWN,
    QW_KEY_LEFT,
    QW_KEY_RIGHT,
    QW_KEY_PGUP,
    QW_KEY_PGDN,
    QW_KEY_HOME,
    QW_KEY_END,
    QW_KEY_ENTER,
    QW_KEY_BACKSPACE,
    QW_KEY_INSERT,
    QW_KEY_TAB,
    QW_KEY_ESC,
    QW_KEY_F1,
    QW_KEY_F2,
    QW_KEY_F3,
    QW_KEY_F4,
    QW_KEY_F5,
    QW_KEY_F6,
    QW_KEY_F7,
    QW_KEY_F8,
    QW_KEY_F9,
    QW_KEY_F10,
    QW_KEY_F11,
    QW_KEY_F12,
    QW_KEY_CTRL_SPACE,
    QW_KEY_CTRL_A,
    QW_KEY_CTRL_B,
    QW_KEY_CTRL_C,
    QW_KEY_CTRL_D,
    QW_KEY_CTRL_E,
    QW_KEY_CTRL_F,
    QW_KEY_CTRL_G,
    QW_KEY_CTRL_H,
    QW_KEY_CTRL_I,
    QW_KEY_CTRL_J,
    QW_KEY_CTRL_K,
    QW_KEY_CTRL_L,
    QW_KEY_CTRL_M,
    QW_KEY_CTRL_N,
    QW_KEY_CTRL_O,
    QW_KEY_CTRL_P,
    QW_KEY_CTRL_Q,
    QW_KEY_CTRL_R,
    QW_KEY_CTRL_S,
    QW_KEY_CTRL_T,
    QW_KEY_CTRL_U,
    QW_KEY_CTRL_V,
    QW_KEY_CTRL_W,
    QW_KEY_CTRL_X,
    QW_KEY_CTRL_Y,
    QW_KEY_CTRL_Z,
    QW_KEY_CTRL_UP,
    QW_KEY_CTRL_DOWN,
    QW_KEY_CTRL_LEFT,
    QW_KEY_CTRL_RIGHT,
    QW_KEY_CTRL_PGUP,
    QW_KEY_CTRL_PGDN,
    QW_KEY_CTRL_HOME,
    QW_KEY_CTRL_END,
    QW_KEY_CTRL_ENTER,
    QW_KEY_CTRL_F1,
    QW_KEY_CTRL_F2,
    QW_KEY_CTRL_F3,
    QW_KEY_CTRL_F4,
    QW_KEY_CTRL_F5,
    QW_KEY_CTRL_F6,
    QW_KEY_CTRL_F7,
    QW_KEY_CTRL_F8,
    QW_KEY_CTRL_F9,
    QW_KEY_CTRL_F10,
    QW_KEY_CTRL_F11,
    QW_KEY_CTRL_F12,
    QW_KEY_ALT_SPACE,
    QW_KEY_ALT_A,
    QW_KEY_ALT_B,
    QW_KEY_ALT_C,
    QW_KEY_ALT_D,
    QW_KEY_ALT_E,
    QW_KEY_ALT_F,
    QW_KEY_ALT_G,
    QW_KEY_ALT_H,
    QW_KEY_ALT_I,
    QW_KEY_ALT_J,
    QW_KEY_ALT_K,
    QW_KEY_ALT_L,
    QW_KEY_ALT_M,
    QW_KEY_ALT_N,
    QW_KEY_ALT_O,
    QW_KEY_ALT_P,
    QW_KEY_ALT_Q,
    QW_KEY_ALT_R,
    QW_KEY_ALT_S,
    QW_KEY_ALT_T,
    QW_KEY_ALT_U,
    QW_KEY_ALT_V,
    QW_KEY_ALT_W,
    QW_KEY_ALT_X,
    QW_KEY_ALT_Y,
    QW_KEY_ALT_Z,
    QW_KEY_ALT_UP,
    QW_KEY_ALT_DOWN,
    QW_KEY_ALT_LEFT,
    QW_KEY_ALT_RIGHT,
    QW_KEY_ALT_PGUP,
    QW_KEY_ALT_PGDN,
    QW_KEY_ALT_HOME,
    QW_KEY_ALT_END,
    QW_KEY_ALT_ENTER,
    QW_KEY_ALT_F1,
    QW_KEY_ALT_F2,
    QW_KEY_ALT_F3,
    QW_KEY_ALT_F4,
    QW_KEY_ALT_F5,
    QW_KEY_ALT_F6,
    QW_KEY_ALT_F7,
    QW_KEY_ALT_F8,
    QW_KEY_ALT_F9,
    QW_KEY_ALT_F10,
    QW_KEY_ALT_F11,
    QW_KEY_ALT_F12,
    QW_KEY_SHIFT_TAB,
    QW_KEY_ALT_MINUS,
    QW_KEY_COUNT
} qw_key_t;

#ifdef __cplusplus
}
#endif

#endif /* QW_KEY_H */
